version: "3"
services:
  serv:
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    logging:
      driver: none
