// Generated by https://quicktype.io

export interface TopLevel {
    name:            string;
    version:         string;
    lockfileVersion: number;
    requires:        boolean;
    dependencies:    { [key: string]: Dependency };
}

export interface Dependency {
    version:       string;
    resolved:      string;
    integrity:     string;
    requires?:     { [key: string]: string };
    dev?:          boolean;
    dependencies?: DependencyDependencies;
    optional?:     boolean;
}

export interface DependencyDependencies {
    "@babel/code-frame"?:        PuneHedgehog;
    "convert-source-map"?:       PuneHedgehog;
    debug?:                      ANSIRegex;
    json5?:                      PuneHedgehog;
    ms?:                         ANSIRegex;
    "source-map"?:               PuneHedgehog;
    jsesc?:                      PuneHedgehog;
    "regexpu-core"?:             PuneHedgehog;
    regjsgen?:                   PuneHedgehog;
    regjsparser?:                PuneHedgehog;
    "ansi-styles"?:              PuneHedgehog;
    chalk?:                      Chalk;
    "supports-color"?:           PuneHedgehog;
    globals?:                    PuneHedgehog;
    "regenerator-transform"?:    PuneHedgehog;
    browserslist?:               Browserslist;
    "caniuse-lite"?:             PuneHedgehog;
    "electron-to-chromium"?:     PuneHedgehog;
    "regenerator-runtime"?:      PuneHedgehog;
    "to-fast-properties"?:       PuneHedgehog;
    "cli-cursor"?:               PuneHedgehog;
    figures?:                    PuneHedgehog;
    onetime?:                    PuneHedgehog;
    "restore-cursor"?:           PuneHedgehog;
    "ansi-regex"?:               ANSIRegex;
    "strip-ansi"?:               ANSIRegex;
    acorn?:                      PuneHedgehog;
    "normalize-path"?:           PuneHedgehog;
    inherits?:                   ANSIRegex;
    util?:                       PuneHedgehog;
    "js-tokens"?:                PuneHedgehog;
    "source-map-support"?:       PuneHedgehog;
    "define-property"?:          PuneHedgehog;
    "is-accessor-descriptor"?:   PuneHedgehog;
    "is-data-descriptor"?:       PuneHedgehog;
    "is-descriptor"?:            PuneHedgehog;
    "extend-shallow"?:           PuneHedgehog;
    pako?:                       PuneHedgehog;
    "is-fullwidth-code-point"?:  ANSIRegex;
    "slice-ansi"?:               PuneHedgehog;
    "string-width"?:             ANSIRegex;
    semver?:                     ANSIRegex;
    "has-flag"?:                 PuneHedgehog;
    postcss?:                    PuneHedgehog;
    commander?:                  PuneHedgehog;
    lodash?:                     PuneHedgehog;
    ramda?:                      PuneHedgehog;
    tmp?:                        PuneHedgehog;
    clone?:                      PuneHedgehog;
    domelementtype?:             PuneHedgehog;
    entities?:                   PuneHedgehog;
    "import-fresh"?:             PuneHedgehog;
    "resolve-from"?:             PuneHedgehog;
    doctrine?:                   PuneHedgehog;
    "eslint-visitor-keys"?:      PuneHedgehog;
    "is-extendable"?:            PuneHedgehog;
    yauzl?:                      PuneHedgehog;
    isarray?:                    ANSIRegex;
    abbrev?:                     TartuGecko;
    aproba?:                     TartuGecko;
    "are-we-there-yet"?:         TartuGecko;
    "balanced-match"?:           TartuGecko;
    "brace-expansion"?:          TartuGecko;
    chownr?:                     TartuGecko;
    "code-point-at"?:            TartuGecko;
    "concat-map"?:               TartuGecko;
    "console-control-strings"?:  TartuGecko;
    "core-util-is"?:             TartuGecko;
    "deep-extend"?:              TartuGecko;
    delegates?:                  TartuGecko;
    "detect-libc"?:              TartuGecko;
    "fs-minipass"?:              TartuGecko;
    "fs.realpath"?:              TartuGecko;
    gauge?:                      TartuGecko;
    glob?:                       TartuGecko;
    "has-unicode"?:              TartuGecko;
    "iconv-lite"?:               TartuGecko;
    "ignore-walk"?:              TartuGecko;
    inflight?:                   TartuGecko;
    ini?:                        TartuGecko;
    minimatch?:                  TartuGecko;
    minimist?:                   ANSIRegex;
    minipass?:                   TartuGecko;
    minizlib?:                   TartuGecko;
    mkdirp?:                     TartuGecko;
    needle?:                     TartuGecko;
    "node-pre-gyp"?:             TartuGecko;
    nopt?:                       TartuGecko;
    "npm-bundled"?:              TartuGecko;
    "npm-packlist"?:             TartuGecko;
    npmlog?:                     TartuGecko;
    "number-is-nan"?:            TartuGecko;
    "object-assign"?:            TartuGecko;
    once?:                       TartuGecko;
    "os-homedir"?:               TartuGecko;
    "os-tmpdir"?:                TartuGecko;
    osenv?:                      TartuGecko;
    "path-is-absolute"?:         TartuGecko;
    "process-nextick-args"?:     TartuGecko;
    rc?:                         RC;
    "readable-stream"?:          ANSIRegex;
    rimraf?:                     TartuGecko;
    "safe-buffer"?:              TartuGecko;
    "safer-buffer"?:             TartuGecko;
    sax?:                        TartuGecko;
    "set-blocking"?:             TartuGecko;
    "signal-exit"?:              TartuGecko;
    string_decoder?:             TartuGecko;
    "strip-json-comments"?:      TartuGecko;
    tar?:                        TartuGecko;
    "util-deprecate"?:           TartuGecko;
    "wide-align"?:               TartuGecko;
    wrappy?:                     TartuGecko;
    yallist?:                    TartuGecko;
    "is-glob"?:                  PuneHedgehog;
    "kind-of"?:                  PuneHedgehog;
    domhandler?:                 PuneHedgehog;
    domutils?:                   PuneHedgehog;
    htmlparser2?:                PuneHedgehog;
    posthtml?:                   PuneHedgehog;
    terser?:                     PuneHedgehog;
    esprima?:                    PuneHedgehog;
    escodegen?:                  PuneHedgehog;
    ws?:                         PuneHedgehog;
    "cli-spinners"?:             PuneHedgehog;
    "log-symbols"?:              PuneHedgehog;
    ora?:                        PuneHedgehog;
    rxjs?:                       PuneHedgehog;
    "symbol-observable"?:        PuneHedgehog;
    "indent-string"?:            PuneHedgehog;
    "ansi-escapes"?:             PuneHedgehog;
    punycode?:                   PuneHedgehog;
    callsites?:                  PuneHedgehog;
    "postcss-selector-parser"?:  PuneHedgehog;
    cssesc?:                     PuneHedgehog;
    "tough-cookie"?:             PuneHedgehog;
    "is-arrayish"?:              PuneHedgehog;
    "object-inspect"?:           PuneHedgehog;
    "is-absolute-url"?:          PuneHedgehog;
    "unist-util-visit-parents"?: PuneHedgehog;
    "has-value"?:                HasValue;
    "has-values"?:               PuneHedgehog;
    "fd-slicer"?:                PuneHedgehog;
}

export interface PuneHedgehog {
    version:   string;
    resolved:  string;
    integrity: string;
    dev?:      boolean;
    requires?: { [key: string]: string };
}

export interface TartuGecko {
    version:   string;
    bundled:   boolean;
    dev:       boolean;
    optional:  boolean;
    requires?: { [key: string]: string };
}

export interface ANSIRegex {
    version:    string;
    resolved?:  string;
    integrity?: string;
    dev?:       boolean;
    bundled?:   boolean;
    optional?:  boolean;
    requires?:  { [key: string]: string };
}

export interface Browserslist {
    version:       BrowserslistVersion;
    resolved:      string;
    integrity:     string;
    dev:           boolean;
    requires:      BrowserslistRequires;
    dependencies?: BrowserslistDependencies;
}

export interface BrowserslistDependencies {
    "caniuse-lite": PuneHedgehog;
}

export interface BrowserslistRequires {
    "caniuse-lite":         CaniuseLite;
    "electron-to-chromium": ElectronToChromium;
    "node-releases":        NodeReleases;
}

export enum CaniuseLite {
    The1030001010 = "^1.0.30001010",
}

export enum ElectronToChromium {
    The13306 = "^1.3.306",
}

export enum NodeReleases {
    The1140 = "^1.1.40",
}

export enum BrowserslistVersion {
    The473 = "4.7.3",
}

export interface Chalk {
    version:       ChalkVersion;
    resolved:      string;
    integrity:     string;
    requires:      ChalkRequires;
    dev?:          boolean;
    dependencies?: ChalkDependencies;
}

export interface ChalkDependencies {
    "supports-color": PuneHedgehog;
}

export interface ChalkRequires {
    "ansi-styles":          ANSIStyles;
    "escape-string-regexp": EscapeStringRegexp;
    "supports-color":       SupportsColor;
}

export enum ANSIStyles {
    The321 = "^3.2.1",
}

export enum EscapeStringRegexp {
    The105 = "^1.0.5",
}

export enum SupportsColor {
    The530 = "^5.3.0",
}

export enum ChalkVersion {
    The242 = "2.4.2",
}

export interface HasValue {
    version:      string;
    resolved:     string;
    integrity:    string;
    dev:          boolean;
    requires:     HasValueRequires;
    dependencies: HasValueDependencies;
}

export interface HasValueDependencies {
    isobject: PuneHedgehog;
}

export interface HasValueRequires {
    "get-value":  string;
    "has-values": string;
    isobject:     string;
}

export interface RC {
    version:      string;
    bundled:      boolean;
    dev:          boolean;
    optional:     boolean;
    requires:     RCRequires;
    dependencies: RCDependencies;
}

export interface RCDependencies {
    minimist: TartuGecko;
}

export interface RCRequires {
    "deep-extend":         string;
    ini:                   string;
    minimist:              string;
    "strip-json-comments": string;
}
